# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3b2c9bb583389774ff5ce2a132c7e2bd"
name = "app-extension"
handle = "app-extension-13"
application_url = "https://construction-municipal-planes-dg.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://construction-municipal-planes-dg.trycloudflare.com/auth/callback",
  "https://construction-municipal-planes-dg.trycloudflare.com/auth/shopify/callback",
  "https://construction-municipal-planes-dg.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
